### ISSUE TITLE
[BUG]  The console outputs a lot of errors

### ISSUE THREAD

**Issue by swe3per** [Darkhax-Minecraft/BotanyTrees#94]
### Minecraft Version

1.20.1

### Mod Version

9.0.17

### Mod Loader

Fabric

### What environment are you running the mod in?

Dedicated Server

### Issue Description

The server starts successfully and the functions seem to be normal. However, the console will output many errors when the server is started and shut down. Maybe it is a problem with the expansion module Botany Pots Ore Planting? Is this normal?
[latest.log](https://github.com/user-attachments/files/17424277/latest.log)
`[23:06:07] [main/ERROR]: Parsing error loading recipe botany_pots_ore_planting:crops/powah/uraninite_ore
com.google.gson.JsonSyntaxException: Unknown item 'powah:uraninite'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:26) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:9) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSON(ISerializer.java:50) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:30) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.method_8121(BasicCropSerializer.java:17) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.7-launcher.1.0.1.jar:1.0.1]
[23:06:07] [main/WARN]: Your custom createaddition:charging/exposed_cut_copper_slab recipe (createaddition:charging/exposed_cut_copper_slab) specified a duration. Durations have no impact on this type of recipe.
[23:06:07] [main/ERROR]: Parsing error loading recipe botany_pots_ore_planting:crops/mythicmetals/manganese_ore
com.google.gson.JsonSyntaxException: Unknown item 'mythicmetals:manganese_ingot'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:26) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:9) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSON(ISerializer.java:50) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:30) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.method_8121(BasicCropSerializer.java:17) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.7-launcher.1.0.1.jar:1.0.1]
[23:06:07] [main/ERROR]: Parsing error loading recipe botany_pots_ore_planting:crops/ad_astra/moon_ice_shard_ore
com.google.gson.JsonSyntaxException: Unknown item 'ad_astra:ice_shard'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:26) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:9) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSON(ISerializer.java:50) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:30) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.method_8121(BasicCropSerializer.java:17) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.7-launcher.1.0.1.jar:1.0.1]
[23:06:07] [main/ERROR]: Parsing error loading recipe botany_pots_ore_planting:soil/gtceu/spessartine_block
com.google.gson.JsonSyntaxException: Unknown item 'gtceu:spessartine_block'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:26) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.SerializerIngredient.fromJSON(SerializerIngredient.java:9) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSON(ISerializer.java:50) ~[Bookshelf-Fabric-1.20.1-20.2.13.jar:?]
	at net.darkhax.botanypots.data.recipes.soil.BasicSoilSerializer.fromJson(BasicSoilSerializer.java:30) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.darkhax.botanypots.data.recipes.soil.BasicSoilSerializer.method_8121(BasicSoilSerializer.java:17) ~[%5B%E5%86%9C%E4%B8%9A%5D%E6%A4%8D%E7%89%A9%E7%9B%86%E6%A0%BDBotanyPots-Fabric-1.20.1-13.0.39.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:950) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:938) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:160) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.16.7-launcher.1.0.1.jar:1.0.1]
`

**Comment by Darkhax** [comment]
This is an issue with botany_pots_ore_planting and not the base mod. Their recipe files do not account for other mods not existing. The errors are harmless but the dev of that addon should update their files if they haven't already to check if the items actually exist before creating the entry.
